 -- ALTER TABLE PRODUCT
 -- MODIFY COLUMN price int;

-- ALTER TABLE PRODUCT
 -- ADD image LONGBLOB not null;


--  ALTER TABLE PRODUCT
--  ADD IMAGE_FILE_NAME VARCHAR(255) not null;

-- ALTER TABLE product
-- DROP COLUMN IMAGE_DATA;


-- ALTER TABLE product
-- ADD image LONGBLOB;
 
 -- ALTER TABLE product
 -- DROP COLUMN id ;

ALTER TABLE PRODUCT CHANGE price ISBN int;

